TRAIN_TARGETS_PARAMS = {
    "target_type": "log",
    "target_cols": [
        "Target_Tomorrow",
        "Target_2_Days",
        "Target_3_Days",
        "Target_5_Days",
        "Target_8_Days",
        "Target_13_Days",
        "Target_21_Days",
        "NextLocalMaxPct",
        "NextLocalMinPct",
        "BarsToNextLocalMax",
        "BarsToNextLocalMin",
    ],
    "shift_targets": [
        {"name": "Tomorrow", "shift": -1},
        {"name": "2_Days", "shift": -2},
        {"name": "3_Days", "shift": -3},
        {"name": "5_Days", "shift": -5},
        {"name": "8_Days", "shift": -8},
        {"name": "13_Days", "shift": -13},
        {"name": "21_Days", "shift": -21},
    ],
    "extrema_window": 10,
}


MODEL_TRAINER_PARAMS = {
    "hidden_size": 64,
    "output_size": 3,
    "seq_len": 20,
    "batch_size": 32,
    "learning_rate": 1e-3,
    "epochs": 10,
    "model_type": "TransformerTCN",
    "grid_buying_threshold": [0.0, 0.01, 0.02, 0.05],
    "grid_selling_threshold": [0.0, 0.005, 0.01, 0.02],
    "grid_profit_target": [0.02, 0.05, 0.1],
    "grid_trailing_stop": [0.02, 0.03, 0.05],
    "weight_decay": 1e-4,
    "val_ratio": 0.2,
    "lr_patience": 5,
    "lr_factor": 0.5,
    "min_lr": 1e-6,
    "early_stopping_patience": 10,
    "target_type": "log",
}
